- id: https://doi.org/10.1109/TIFS.2021.3050061
- id: https://doi.org/10.1109/TIP.2021.3097175
- id: https://openaccess.thecvf.com/content/WACV2022W/CV4WS/html/Roygaga_APE-V_Athlete_Performance_Evaluation_Using_Video_WACVW_2022_paper.html
- id: https://link.springer.com/chapter/10.1007/978-981-16-7621-5_15