
- id: https://doi.org/10.1109/TIFS.2021.3050061
  image: https://www.google.com/url?sa=i&url=https%3A%2F%2Flink.springer.com%2Fchapter%2F10.1007%2F978-981-16-7621-5_15&psig=AOvVaw3LpTDMGew4I_IYZvrCyJH8&ust=1757367520680000&source=images&cd=vfe&opi=89978449&ved=0CBYQjRxqFwoTCJDYhK7Ox48DFQAAAAAdAAAAABAE